---
- name: Mulitvendor data models
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather interface data model for all
      include_tasks: "{{ ansible_network_os }}.yml"

    - name: Store interface data as host_vars
      copy:
        content: "{{ {{ ansible_network_os }}_interfaces | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}/{{ ansible_network_os }}_interfaces.yml }}"
