---
- name: Initialize Git
  hosts: ansible-1
  gather_facts: no
  become: yes
  vars:
    git_url: git@github.com:termlen0/resource-modules.git
    git_key: "{{ lookup('file', secret_key) }}"
    git_branch: master

  tasks:
    - name: git pull
      include_role:
        name: ansible-git
        tasks_from: pull

    - name: remove files
      file:
        path: "{{ playbook_dir }}/resource-modules/host_vars/*"
        state: absent

- name: Mulitvendor data models
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather interface data model for all
      include_tasks: "{{ ansible_network_os }}.yml"
      when: ansible_network_os is defined

    - name: Block of actions
      block:
        - name: Store interface data as host_vars
          copy:
            content: "{{ hostvars[inventory_hostname][ansible_network_os +  '_interfaces'].gathered | to_nice_yaml }}"
            dest: "{{ playbook_dir }}/resource-modules/host_vars/{{ inventory_hostname }}/{{ ansible_network_os }}_interfaces.yml"

        - name: Add Dictionary key for interfaces
          lineinfile:
            path: "{{ playbook_dir }}/resource-modules/host_vars/{{ inventory_hostname }}/{{ ansible_network_os }}_interfaces.yml"
            state: present
            insertbefore: BOF
            line: "interfaces:"

        - name: Store l2 interface data as host_vars
          copy:
            content: "{{ hostvars[inventory_hostname][ansible_network_os +  '_l2interfaces'].gathered | to_nice_yaml }}"
            dest: "{{ playbook_dir }}/resource-modules/host_vars/{{ inventory_hostname }}/{{ ansible_network_os }}_l2_interfaces.yml"

        - name: Add Dictionary key for L2interfaces
          lineinfile:
           path: "{{ playbook_dir }}/resource-modules/host_vars/{{ inventory_hostname }}/{{ ansible_network_os }}_l2_interfaces.yml"
           state: present
           insertbefore: BOF
           line: "l2_interfaces:"

        - name: Store l3 interface data as host_vars
          copy:
            content: "{{ hostvars[inventory_hostname][ansible_network_os +  '_l3interfaces'].gathered | to_nice_yaml }}"
            dest: "{{ playbook_dir }}/resource-modules/host_vars/{{ inventory_hostname }}/{{ ansible_network_os }}_l3_interfaces.yml"

        - name: Add Dictionary key for L2interfaces
          lineinfile:
            path: "{{ playbook_dir }}/resource-modules/host_vars/{{ inventory_hostname }}/{{ ansible_network_os }}_l3_interfaces.yml"
            state: present
            insertbefore: BOF
            line: "l3_interfaces:"
      delegate_to: localhost
      when: ansible_network_os is defined

- name: Update Git
  hosts: ansible-1
  gather_facts: no
  become: yes
  vars:
    git_url: git@github.com:termlen0/resource-modules.git
    git_key: "{{ lookup('file', secret_key) }}"
    git_branch: master

  tasks:

    - name: Update SoT
      include_role:
        name: ansible-git
        tasks_from: push
