---
- name: Mulitvendor - REPLACE
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather interface data model for all
      include_tasks: "replace_{{ ansible_network_os }}.yml"
      when: ansible_network_os is defined
