---

#### Get the archived config ####
- name: ENSURE THAT A LOCAL ARCHIVE PATH EXISTS
  file:
    path: "/archived_configs"
    state: directory
    mode: 0777
  delegate_to: ansible-1
  run_once: yes
  become: yes

- name: GATHER THE ARCHIVED CONFIGS
  git:
    repo: "{{ sot_repo }}"
    clone: yes
    dest: "/archived_configs"
    key_file: "{{ secret_key }}" #Passed in from Tower git creds
    accept_hostkey: true
  delegate_to: localhost
  run_once: yes

#### Now get the running config ####
- name: ENSURE THAT THE DIR TO STORE RUNNING CONFIGS EXITS
  file:
    path: "/running_configs"
    state: directory
    mode: 0777
  delegate_to: ansible-1
  run_once: yes
  become: yes

- name: GET THE RUNNING CONFIG
  include_tasks: "{{ ansible_network_os }}.yml"

#### Check for differences
- name: CHECK IF OOB CHANGES EXIST
  command: >-
    diff "{{ running }}"  "{{ archived }}"
  register: difference
  failed_when: difference.rc > 1
  changed_when: difference.rc == 1
  delegate_to: localhost
  run_once: true

- name: DISPLAY DIFFERENCES
  debug:
    var: difference.stdout
  when: difference.rc != 0
  delegate_to: localhost
  run_once: true

- name: FAIL IF THERE ARE DIFFERENCES
  fail:
    msg: "Running configs do not match the source of truth!"
  when: difference.rc != 0
